### ISSUE TITLE
Crawling fails after the redesign of LVZ website (since 02.03.2022)

### ISSUE THREAD

**Issue by sepe81** [CodeforLeipzig/lvz-viz#100]
Since 02 March 2022 all articles under http://www.lvz.de/Leipzig/Polizeiticker/Polizeiticker-Leipzig/ are dead links (not found).

The new starting page is https://www.lvz.de/themen/leipzig-polizei/ and the site structure and pagination has totally changed.

**Comment by inpercima** [comment]
The link for "Leistungsschutzrecht" is also no longer available under http://www.lvz-online.de/nachrichten/service/impressum/servicetexte/leistungsschutzrecht/r-servicetexte-a-199230.html

I haven't found a direct replacement for it.

**Comment by sepe81** [comment]
I created https://github.com/CodeforLeipzig/lvz-viz/issues/100 as a follow-up.
