### ISSUE TITLE
crawl all articles

### ISSUE THREAD

**Issue by spinner0815** [CodeforLeipzig/lvz-viz#13]
currently there are only articles till 2011. But on lvz there are articles till 2009. The crawler only crawl all page when the index is empty. But if an error appears the crawler stops. So it stops in the middle of the articles and did not get to them again. 
Therefore a better crawler has to be in place.

Idea:
* store the main pages and the corresponding detailpages. check the index if the detail pages all in it. If not crawl the pages. 
(http://nachrichten.lvz-online.de/leipzig/polizeiticker/polizeiticker-leipzig/r-polizeiticker-leipzig-seite-334.html)

**Comment by sepe81** [comment]
Hey @spinner0815, would be fine if you could review c8f046a on occasion (including commit comments).
