### ISSUE TITLE
http://leipzig.codefor.de/lvz-viz/ shows no entries anymore

### ISSUE THREAD

**Issue by joergreichert** [CodeforLeipzig/lvz-viz#31]
http://leipzig.codefor.de/lvz-viz/ shows no entries anymore, it seems that the service is currently down, as http://leipzig.codefor.de/lvz-viz/api/last7days shows:

"Service Unavailable

The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later."

**Comment by RicardoUsbeck** [comment]
Dear @joergreichert please ask @keimlink to add you as team member to this repository. The original team needed to discontinue work on this project unfortunately.

**Comment by sepe81** [comment]
@joergreichert This is already fixed in https://github.com/CodeforLeipzig/lvz-viz/issues/23 but we need a redeployment.

@keimlink I don't have any access to the webserver till now. Can we this remote or better at the OK-Lab-Leipzig meeting?

**Comment by keimlink** [comment]
@sepe81 I will be at the meeting tonight. But we can also discuss this on Slack. :smile:

**Comment by sepe81** [comment]
The new deployment is under https://lvz-viz.leipzig.codefor.de/ but we need to fix another bug according to https. I file an issue.

**Comment by sepe81** [comment]
The updated app now successfully runs at https://lvz-viz.leipzig.codefor.de

The old link currently redirects to https://cologne.codefor.de/lvz-viz (don't know why).

@keimlink Are you able to update the website url at http://codefor.de/projekte/2014-07-01-le-lvz_polizeiticker_visualisierung ?
