### ISSUE TITLE
Use standalone Elasticsearch instance

### ISSUE THREAD

**Issue by joergreichert** [CodeforLeipzig/lvz-viz#47]
this implies also migration to spring boot 2.0.2.RELEASE

https://stackoverflow.com/questions/44770929/embedded-elasticsearch-is-not-accessible-from-outside
https://github.com/JahnelGroup/spring-boot-samples/tree/master/spring-boot-elasticsearch-5.x
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Migration-Guide

**Comment by sepe81** [comment]
@joergreichert Some days ago I also started working on the Spring Boot 2 migration under https://github.com/sepe81/lvz-viz/commits/spring-boot-2  But it's not finished yet.

**Comment by joergreichert** [comment]
Haven't seen that, sorry. 

This issue is also not done yet, as somehow the Elasticsearch client cannot find any node for the given Elasticsearch URL, maybe due to a mismatch of versions (ES version, ES client version, SpringData version, etc.) or misconfiguration. Still under investigation.

**Comment by sepe81** [comment]
I just merged the Spring Boot 2.2 migration with working support for a separate ES container (version 6.4.3).

As a next step we need a concept for migrating the existing (productive) data.
